services:
  auctions:
    build:
      context: ./auction-service
      dockerfile: Dockerfile
    container_name: auction-service
    depends_on:
      auctions-db:
        condition: service_healthy
    environment:
      - ENV=${APP_ENV}
      - CONFIG_PATH=/config
      - APP_ENV=local
      - MIGRATIONS_DIR=${MIGRATIONS_DIR}
      - JWT_PUBLIC_KEY_PATH=${JWT_PUBLIC_KEY_PATH}
  bidders:
    build:
      context: ./bidder-service
      dockerfile: Dockerfile
    container_name: bidders-service
    environment:
      - ENV=${APP_ENV}
      - CONFIG=/config
      - MIGRATIONS_DIR=${MIGRATIONS_DIR}
    depends_on:
      bidders-db:
        condition: service_healthy
    networks:
      - app-net
  auth-service:
    build:
      context: ./auth-service
      dockerfile: Dockerfile
    container_name: auth-service
    depends_on:
      auth-db:
        condition: service_healthy
      auth-redis:
        condition: service_healthy
    networks:
      - app-net
    environment:
      - ENV=${APP_ENV}
      - CONFIG=/config
      - MIGRATIONS_DIR=${MIGRATIONS_DIR}
  auctions-db:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    healthcheck:
      start_period: 10s
      timeout: 1m
      interval: 10s
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
    ports:
      - "3307:3306"
  bidders-db:
    image: mysql:latest
    container_name: bidders-db
    environment:
      - MYSQL_ROOT_PASSWORD=admin
    healthcheck:
      start_period: 10s
      timeout: 1m
      interval: 10s
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
    ports:
      - "3308:3306"
    networks:
      - app-net
  auth-redis:
    image: redis:latest
    container_name: redis-server
    environment:
      - REDIS_PASSWORD=admin
    ports:
      - "6379:6379"
    networks:
      - app-net
  auth-db:
    image: mysql:latest
    container_name: auth-db
    environment:
      - MYSQL_ROOT_PASSWORD=admin
    healthcheck:
      start_period: 10s
      timeout: 1m
      interval: 10s
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
    ports:
      - "3309:3306"
    networks:
      - app-net
  rabbit:
    image: rabbitmq
    container_name: rabbit-mq
    environment:
      - RABBIT_USER=${RABBIT_USER}
      - RABBIT_PASSWORD=${RABBIT_PASSWORD}
    healthcheck:
      test: [ "CMD", "rabbitmq-diagnostics", "ping" ]
      start_period: 1s
      timeout: 1m
      interval: 10s
    ports:
      - "5672:5672"
      - "15672:15672"

networks:
  app-net:
    driver: bridge

