server:
  port: 8099

database:
  port: 3306
  host: "localhost"
  user: "root"
  password: "admin"
aws:
  bucket: "bucket_name"
  region: "region"
  secret: "auth_public_key"
redis:
  port: 6379
  host: "localhost:6379"
  password: "admin"