database:
  host: "auctions-db"
  port: 3306
  user: "root"
  password: "admin"

server:
  port: "8090"
  secret: "auth_public_key"

redis:
  port: 6379
  host: "redis"
  user: "admin"
  password: "${REDIS_PASSWORD}"