database:
  host: "localhost"
  port: 3307
  user: "root"
  password: "admin"

server:
  port: "8090"
  secret: "auth_public_key"
aws:
  s3_buckets:
    primary: "item_pictures"
  region: "us-east-1"


redis:
  port: 6379
  host: "localhost"
  user: "admin"
  password: "${REDIS_PASSWORD}"